; =============================================================================
; C3 Music Receiver
; ESP32-C3 + SSD1306 72x40 OLED + UDA1334A I2S DAC
; =============================================================================

[platformio]
default_envs = c3music

[env:c3music]
platform = espressif32@6.8.1
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder
    time

upload_speed = 460800

build_type = release

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    olikraus/U8g2@^2.36.5

lib_ldf_mode = chain+

board_build.f_cpu = 160000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
